
default: build

[group("build")]
build: build-chrome build-firefox

[private]
build-one browser:
  #!/usr/bin/env bash
  set -euo pipefail

  root="$(git rev-parse --show-toplevel)"

  out_path="$(nix build --no-link --print-out-paths "$root#extension-{{browser}}")"

  rm -rf "dist-{{browser}}" "dist-{{browser}}.zip"
  cp -rL "$out_path/dist-{{browser}}" "./dist-{{browser}}"
  cp -L "$out_path/dist-{{browser}}.zip" "./dist-{{browser}}.zip"
  chmod -R u+w "dist-{{browser}}" "dist-{{browser}}.zip"

[group("build")]
build-chrome: (build-one "chrome")

[group("build")]
build-firefox: (build-one "firefox")

[group("operational")]
deploy-firefox: build-firefox
  #!/usr/bin/env bash
  set -euo pipefail

  set -a
  source .secrets-firefox.env
  set +a

  npx \
    --no \
    web-ext sign \
    --source-dir dist-firefox \
    --channel=listed \
    --amo-metadata=zz-firefox-amo-metadata.json \
    --api-key="$jwt_issuer" \
    --api-secret="$jwt_secret"
