// Code generated by dagnabit; DO NOT EDIT.

package browser_items

import internal "code.linenisgreat.com/chrest/go/internal/charlie/browser_items"

type (
	BrowserProxy                      = internal.BrowserProxy
	BrowserRequestGet                 = internal.BrowserRequestGet
	BrowserRequestPut                 = internal.BrowserRequestPut
	HTTPResponseWithRequestPayloadGet = internal.HTTPResponseWithRequestPayloadGet
	HTTPResponseWithRequestPayloadPut = internal.HTTPResponseWithRequestPayloadPut
	Item                              = internal.Item
	ItemId                            = internal.ItemId
	RequestPayloadGet                 = internal.RequestPayloadGet
	RequestPayloadPut                 = internal.RequestPayloadPut
	Url                               = internal.Url
)
