// Code generated by dagnabit (0.4.1+6c645d3); DO NOT EDIT.

package browser_items

import internal "code.linenisgreat.com/chrest/go/internal/charlie/browser_items"

type BrowserProxy = internal.BrowserProxy
type BrowserRequestGet = internal.BrowserRequestGet
type BrowserRequestPut = internal.BrowserRequestPut
type HTTPResponseWithRequestPayloadGet = internal.HTTPResponseWithRequestPayloadGet
type HTTPResponseWithRequestPayloadPut = internal.HTTPResponseWithRequestPayloadPut
type Item = internal.Item
type ItemId = internal.ItemId
type RequestPayloadGet = internal.RequestPayloadGet
type RequestPayloadPut = internal.RequestPayloadPut
type Url = internal.Url
