// Code generated by tommy 0.4.4 (054f61d); DO NOT EDIT.

package config_toml

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ConfigDocument struct {
	data   Config
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDefaultBrowser, _ok := model.Get("default-browser"); _ok && _vDefaultBrowser.Kind == cst.VTable {
		_vDefaultBrowser.MarkSeen()
		if _vDefaultBrowserBrowser, _ok := _vDefaultBrowser.Get("browser"); _ok && _vDefaultBrowserBrowser.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDefaultBrowserBrowser.Leaf); _xok {
				if err := d.data.DefaultBrowser.Browser.UnmarshalText([]byte(_x)); err != nil {
					return nil, fmt.Errorf("browser: %w", err)
				}
				_vDefaultBrowserBrowser.MarkConsumed()
			}
		}
		if _vDefaultBrowserId, _ok := _vDefaultBrowser.Get("id"); _ok && _vDefaultBrowserId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDefaultBrowserId.Leaf); _xok {
				d.data.DefaultBrowser.Id = _x
				_vDefaultBrowserId.MarkConsumed()
			}
		}
	} else {
		if _vBrowser, _ok := model.Get("browser"); _ok && _vBrowser.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vBrowser.Leaf); _xok {
				if err := d.data.DefaultBrowser.Browser.UnmarshalText([]byte(_x)); err != nil {
					return nil, fmt.Errorf("browser: %w", err)
				}
				_vBrowser.MarkConsumed()
			}
		}
		if _vId, _ok := model.Get("id"); _ok && _vId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
				d.data.DefaultBrowser.Id = _x
				_vId.MarkConsumed()
			}
		}
	}
	return d, nil
}

func (d *ConfigDocument) Data() *Config {
	return &d.data
}

func (d *ConfigDocument) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "default-browser")
		{
			v, err := d.data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("browser: %w", err)
			}
			if err := cst.SetAny(tableNode, "browser", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.DefaultBrowser.Id != "" {
			if err := cst.SetAny(tableNode, "id", d.data.DefaultBrowser.Id); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "id")
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigInto(data *Config, sub *cst.Value) error {
	if _vDefaultBrowser, _ok := sub.Get("default-browser"); _ok && _vDefaultBrowser.Kind == cst.VTable {
		_vDefaultBrowser.MarkSeen()
		if _vDefaultBrowserBrowser, _ok := _vDefaultBrowser.Get("browser"); _ok && _vDefaultBrowserBrowser.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDefaultBrowserBrowser.Leaf); _xok {
				if err := data.DefaultBrowser.Browser.UnmarshalText([]byte(_x)); err != nil {
					return fmt.Errorf("browser: %w", err)
				}
				_vDefaultBrowserBrowser.MarkConsumed()
			}
		}
		if _vDefaultBrowserId, _ok := _vDefaultBrowser.Get("id"); _ok && _vDefaultBrowserId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDefaultBrowserId.Leaf); _xok {
				data.DefaultBrowser.Id = _x
				_vDefaultBrowserId.MarkConsumed()
			}
		}
	} else {
		if _vBrowser, _ok := sub.Get("browser"); _ok && _vBrowser.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vBrowser.Leaf); _xok {
				if err := data.DefaultBrowser.Browser.UnmarshalText([]byte(_x)); err != nil {
					return fmt.Errorf("browser: %w", err)
				}
				_vBrowser.MarkConsumed()
			}
		}
		if _vId, _ok := sub.Get("id"); _ok && _vId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
				data.DefaultBrowser.Id = _x
				_vId.MarkConsumed()
			}
		}
	}
	return nil
}

func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "default-browser")
		{
			v, err := data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return fmt.Errorf("browser: %w", err)
			}
			if err := cst.SetAny(tableNode, "browser", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.DefaultBrowser.Id != "" {
			if err := cst.SetAny(tableNode, "id", data.DefaultBrowser.Id); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "id")
		}
	}
	return nil
}
