// Code generated by dagnabit (0.6.2+9d069d9); DO NOT EDIT.

package client

import internal "code.linenisgreat.com/chrest/go/internal/delta/client"

type (
	BrowserItem                = internal.BrowserItem
	BrowserItemId              = internal.BrowserItemId
	BrowserProxy               = internal.BrowserProxy
	BrowserRequest             = internal.BrowserRequest
	ResponseWithParsedJSONBody = internal.ResponseWithParsedJSONBody
)

var (
	ResponseFromReader  = internal.ResponseFromReader
	ResponseFromRequest = internal.ResponseFromRequest
)
