// Code generated by dagnabit (0.4.1+6c645d3); DO NOT EDIT.

package client

import internal "code.linenisgreat.com/chrest/go/internal/delta/client"

type BrowserItem = internal.BrowserItem
type BrowserItemId = internal.BrowserItemId
type BrowserProxy = internal.BrowserProxy
type BrowserRequest = internal.BrowserRequest
type ResponseWithParsedJSONBody = internal.ResponseWithParsedJSONBody

var ResponseFromReader = internal.ResponseFromReader
var ResponseFromRequest = internal.ResponseFromRequest
